name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0' # Specify the PHP version you want to use

      - name: Install dependencies
        run: composer install

      - name: Build Docker image
        run: |
          docker build -t my-php-app .

      - name: Docker login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        # Este passo garante que o login no Docker foi realizado com sucesso

      - name: Tag and Push Docker image
        run: |
          docker tag my-php-app ${{ secrets.DOCKER_USERNAME }}/my-php-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-php-app:latest
        # O nome do repositório Docker precisa ser ${{ secrets.DOCKER_USERNAME }}/my-php-app (se for no Docker Hub)

      - name: Deploy
        run: |
          # Add your deployment commands here
          echo "Deploying the application..."
