name: Delete Branch After Merge

on:
  pull_request:
    types:
      - closed

jobs:
  delete_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Delete branch after merge (except main and dev)
        if: github.event.pull_request.merged == true && github.event.pull_request.base.ref != 'main' && github.event.pull_request.base.ref != 'dev'
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Deleting branch: $BRANCH_NAME"
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin --delete $BRANCH_NAME
