name: Deploy com Dupla Aprovação

on:
  push:
    branches:
      - main
      - "hotfix/*"  # Permitir deploy de branches hotfix

jobs:
  request-first-approval:
    runs-on: ubuntu-latest
    environment:
      name: Primeira-Aprovacao
    outputs:
      first_approver: ${{ github.actor }}
    steps:
      - name: Aguardando primeira aprovação
        run: echo "Primeira aprovação concedida por $GITHUB_ACTOR"

  request-second-approval:
    needs: request-first-approval
    runs-on: ubuntu-latest
    environment:
      name: Segunda-Aprovacao
    steps:
      - name: Garantir que é um segundo aprovador
        run: |
          if [[ "${{ github.actor }}" == "${{ needs.request-first-approval.outputs.first_approver }}" ]]; then
            echo "Erro: O mesmo usuário não pode aprovar duas vezes!"
            exit 1
          fi
      - name: Aguardando segunda aprovação
        run: echo "Segunda aprovação concedida por $GITHUB_ACTOR"

  deploy:
    needs: [request-first-approval, request-second-approval]
    runs-on: ubuntu-latest
    steps:
      - name: Executar Deploy
        run: echo "Deploy realizado!"
