name: Deploy com Dupla Aprovação

on:
  push:
    branches:
      - main

jobs:
  request-first-approval:
    runs-on: ubuntu-latest
    environment:
      name: Primeira-Aprovacao
    outputs:
      approver: ${{ github.actor }}
    steps:
      - name: Aguardando primeira aprovação
        run: echo "Primeira aprovação concedida por $GITHUB_ACTOR"

  request-second-approval:
    needs: request-first-approval
    runs-on: ubuntu-latest
    if: always()
    environment:
      name: Segunda-Aprovacao
    steps:
      - name: Aguardando segunda aprovação
        run: echo "Segunda aprovação concedida por $GITHUB_ACTOR"

  deploy:
    needs: [request-first-approval, request-second-approval]
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Executar Deploy
        run: echo "Deploy realizado!"
