name: Deploy com Dupla Aprovação

on:
  push:
    branches:
      - main
      - "hotfix/*"  # Permitir deploy de branches hotfix

jobs:
  check-user:
    runs-on: ubuntu-latest
    outputs:
      is_admin: ${{ steps.check.outputs.is_admin }}
    steps:
      - name: Verificar se usuário é administrador
        id: check
        run: |
          ADMINS="joaovictor-ip4y outro-admin" # Lista de admins
          if echo "$ADMINS" | grep -w "$GITHUB_ACTOR"; then
            echo "is_admin=true" >> "$GITHUB_ENV"
          else
            echo "is_admin=false" >> "$GITHUB_ENV"
          fi
      - name: Salvar saída
        run: echo "is_admin=${{ env.is_admin }}" >> "$GITHUB_OUTPUT"

  request-first-approval:
    needs: check-user
    if: needs.check-user.outputs.is_admin == 'false'
    runs-on: ubuntu-latest
    environment:
      name: Primeira-Aprovacao
    outputs:
      approver: ${{ github.actor }}
    steps:
      - name: Aguardando primeira aprovação
        run: echo "Primeira aprovação concedida por $GITHUB_ACTOR"

  request-second-approval:
    needs: request-first-approval
    runs-on: ubuntu-latest
    if: needs.request-first-approval.outputs.approver != 'joaovictor-ip4y' && needs.request-first-approval.outputs.approver != 'outro-admin'
    environment:
      name: Segunda-Aprovacao
    steps:
      - name: Aguardando segunda aprovação
        run: echo "Segunda aprovação necessária..."

  deploy:
    needs: [check-user, request-second-approval]
    if: needs.check-user.outputs.is_admin == 'true' || success()
    runs-on: ubuntu-latest
    environment:
      name: Production
    steps:
      - name: Executar Deploy
        run: echo "Deploy realizado!"
