name: PHP Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPUnit tests
        run: |
          echo '```' > test-results.txt
          vendor/bin/phpunit --testdox >> test-results.txt
          echo '```' >> test-results.txt

      - name: Create or update comment with test results
        if: always()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ✅ PHP Test Results
            **PHP Version:** 8.3  
            **Composer Dependencies:** Installed  
            **Test Summary:**  
            $(cat test-results.txt)
