name: PHP Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run tests
        run: vendor/bin/phpunit --log-junit junit.xml

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: junit.xml

      - name: Create or update comment
        if: always()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## PHP Test Results
            The tests have completed.
            You can find the detailed test results in the [Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
