name: PHP Tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: mbstring, intl, apcu
          ini-values: post_max_size=256M, upload_max_filesize=256M
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run tests
        run: vendor/bin/phpunit --log-junit junit.xml
        continue-on-error: true

      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: junit.xml

      - name: Create or update comment
        if: always()
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ${{ github.repository }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## PHP Test Results
            The tests have completed.
            You can find the detailed test results in the [Artifacts](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).
            ```
            ${{ steps.test.outputs.test-results }}
            ```