name: PHP Tests

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, xdebug

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Run PHPUnit tests with coverage
        continue-on-error: true  # Continua mesmo se os testes falharem
        run: |
          vendor/bin/phpunit --coverage-text --log-junit junit.xml | tee test-results.txt

      - name: Extract coverage and test details
        id: extract
        run: |
          COVERAGE=$(grep -oP 'Lines:\s+\K[0-9]+\.[0-9]+' test-results.txt || echo "0.00")
          TOTAL_TESTS=$(grep -oP 'Tests:\s+\K[0-9]+' test-results.txt || echo "0")
          FAILURES=$(grep -oP 'Failures:\s+\K[0-9]+' test-results.txt || echo "0")
          SKIPPED=$(grep -oP 'Skipped:\s+\K[0-9]+' test-results.txt || echo "0")
          EXEC_TIME=$(grep -oP 'Time:\s+\K[0-9\.]+' test-results.txt || echo "0.00")

          echo "coverage=$COVERAGE" >> $GITHUB_ENV
          echo "total_tests=$TOTAL_TESTS" >> $GITHUB_ENV
          echo "failures=$FAILURES" >> $GITHUB_ENV
          echo "skipped=$SKIPPED" >> $GITHUB_ENV
          echo "exec_time=$EXEC_TIME" >> $GITHUB_ENV

      - name: Create or update comment with test results
        if: always()
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## ✅ PHPUnit Test Coverage Report
            **Total Coverage:** ${{ env.coverage }}%  
            **Total Tests:** ${{ env.total_tests }}  
            **Failures:** ${{ env.failures }}  
            **Skipped:** ${{ env.skipped }}  
            **Execution Time:** ${{ env.exec_time }} seconds
